name: Release create-next-app-with-gluestack-ui

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  release:
    name: Publish version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies (prevent updates to lock file)
        run: yarn
      - name: Install dependencies (prevent updates to lock file)
        run: yarn
      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Post to a Slack channel
        id: slack
        if: steps.changesets.outputs.published == 'true'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: C05H3MUMPN3
          slack-message: "A new package was published in ${{ github.event.repository.name }}!\n${{ toJSON(steps.changesets.outputs.publishedPackages) }}"
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
